### ISSUE TITLE
[v3.4] Authentication Bug

### ISSUE THREAD

**Issue by schmees-uol** [bigbluebutton/greenlight#5942]
We are using Greenlight-v3.4 with Keycloak. Users who were migrated from v2 and did not log into v3.x, yet, cannot log into v3.4 anymore. In the database table "users" the "external_id"-field of all affected users is set to the original LDAP-path that came with v2. v3.3.6 properly changed this external_id-field from the user's individual LDAP-path to her individual keycloak-id after authentication and thereby login was possible. This isn't working in v3.4 anymore. Instead, we get an "Email has already been taken"-error (see pic). There is something wrong with your internal workflows or mapping.
![gl-bug](https://github.com/user-attachments/assets/6233573c-c5e9-4e5a-9017-0934e579aa05)

This is independent from the new field "Allowed Email Domains" in the site-settings. If Keycloak delivers a non-valid e-mail-address, you'll get an "undefined method 'render_error'" (see pic).
![gl-bug2](https://github.com/user-attachments/assets/41b2c5d7-55e0-4863-a248-c4078c46004f)

**Comment by danielwujecki** [comment]
We have experienced this as well. All users who have only logged into greenlight v2 and haven't used greenlight v3 are unable to log into greenlight v3. I can confirm that the reason seems to be that the `external_id` field in the `users` table is not updated properly and is still set to the ldap uid instead of the keycloak-id. When I manually update the `external_id` to the corresponding keycloak-id of the user, they are able to log in.

**Comment by Ithanil** [comment]
Here is the PR which allows enabling the old fallback behavior via a flag: https://github.com/bigbluebutton/greenlight/pull/5930

**Comment by farhatahmad** [comment]
Fixed in the latest release
